#index:
#    path: /
#    controller: App\Controller\DefaultController::index

## RUTAS PARA CONTROLADOR USUARIO ##
##user:
#   path: /user
#   controller: App\Controller\UserController::index

register:
   path: /user/register
   controller: App\Controller\UserController::create
   methods: [POST]

login:
   path: /user/login
   controller: App\Controller\UserController::login
   methods: [POST]

   #edit:
   #   path: /user/edit
   #  controller: App\Controller\UserController::edit
   #  methods: [POST]

## RUTAS PARA CONTROLADOR SUBASTA ##
subastaCreate:
   path: /subasta/create
   controller: App\Controller\SubastaController::create
   methods: [POST]

getSubastas:
   path: /subasta/list
   controller: App\Controller\SubastaController::getSubastas
   methods: [GET]

getSubastasUser:
   path: /subasta/user/list
   controller: App\Controller\SubastaController::getSubastasUser
   methods: [GET]


## RUTAS PARA CONTROLADOR LOTE ##
loteCreate:
   path: /lote/create
   controller: App\Controller\LoteController::create
   methods: [POST]

getLotesSubasta:
   path: /lote/subasta/{id}
   controller: App\Controller\LoteController::getLotesSubasta
   methods: [GET]

## RUTAS PARA CONTROLADOR ARTICULO ##
articuloCreate:
   path: /articulo/create
   controller: App\Controller\ArticuloController::create
   methods: [POST]

## RUTAS PARA CONTROLADOR PUJA ##
pujaCreate:
   path: /puja/create
   controller: App\Controller\PujaController::create
   methods: [POST]

getPujasUser:
   path: /puja/user/list
   controller: App\Controller\PujaController::getPujasUser
   methods: [GET]

getPujasSubasta:
   path: /puja/subasta/{id}
   controller: App\Controller\PujaController::getPujasSubasta
   methods: [GET]